### GET Trays

GET http://localhost:1222/trays


### GET One tray

GET http://localhost:1222/trays/f63c2901-87cb-4faf-abf2-1fd519a8acbd

### POST new tray
POST http://localhost:1222/trays/
Content-Type: application/json

{
  "productId": 15,
  "trayComment": "Esta es otra prueba",
  "categoryId": 1,
  "trayStatus": true,
  "trayQuality": "Excelente",
  "trayPercentage": 100,
  "createdBy": "4ee96546-1a65-410d-adf5-eb1ad7b4c07c"
}

### PATCH
PATCH http://localhost:1222/trays/65de370b-1e88-4c0c-9dc1-d9cf3f3009cf
Content-Type:  application/json

{
  "productId": 9,
  "trayQuality": "Regular",
  "trayComment": "Woooo",
  "trayPercentage": 80
}


###

{
  "productId": 25,
  "trayComment": "Este es un cambio",
  "categoryId": 1,
  "trayStatus": 1,
  "trayQuality": "Regular",
  "trayPercentage": 80
}

### DELETE

DELETE http://localhost:1222/trays/f63c2901-87cb-4faf-abf2-1fd519a8acbd
